name: UI Backend CI
on:
  push:
    paths:
      - 'ui-backend/**'
  pull_request:
    paths:
      - 'ui-backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: ./gradlew :ui-backend:build --no-daemon
